name: New Horizon Baptist Fellowship
favicon: null
layout_spectrum: 0.24457
typography_spectrum: 0.3825954
title: 'New Horizon Baptist Fellowship: Finding in Christ our Greatest delight'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#373737'
    - '#f9f8fd'
    - '#74716b'
    - '#cbccd1'
    - '#0b0d0c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
