name: New Horizon Baptist Fellowship
favicon: null
layout_spectrum: 0.2401434
typography_spectrum: 0.3825954
title: Finding in Christ our Greatest delight
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020302'
    - '#FCFCFD'
    - '#4B4239'
    - '#87786F'
    - '#BEB2AC'
  brandStrength: 0.5340502
  lightness: 0.2666942
  saturation: 0.5120634
  rhythmicContrast: 0.2531474
purpose: []
